### ISSUE TITLE
Misleading label on the button that sends an airdrop

### ISSUE THREAD

**Issue by alexputkov-da** [maxhsu-da/wallet-refapp#67]
The button that sends an airdrop has label "SEND", which is replaced with "DONE" after the button is clicked. Consequent clicking on this button, which is now labeled "DONE" sends additional airdrops. This is misleading. One way to fix this is to disable the button after it's been clicked, thus disallowing more than one airdrop to the same user without reloading the HTML page. When the user reloads the page (by navigating to another page and back or by refreshing the browser) the button label will revert to "SEND" and the button will be enabled.

**Comment by maxhsu-da** [comment]
Fixed in #85
