### ISSUE TITLE
Create visual indication that Reference is an optional field

### ISSUE THREAD

**Issue by alexputkov-da** [maxhsu-da/wallet-refapp#68]
The page under the Create tab has no visual indication that Reference is an optional field. The description text underneath the field says that it's optional, but it would be great to add a visual indication.

**Comment by maxhsu-da** [comment]
<img width="296" alt="Screenshot 2022-04-15 at 12 18 37 PM" src="https://user-images.githubusercontent.com/97971317/163623011-418c4f2b-7d5b-447c-a531-88f14781b520.png">

Put it in explicitly in the text - quickest and clear way atm.
