### ISSUE TITLE
Blurbs

### ISSUE THREAD

**Issue by rikotacards** [maxhsu-da/wallet-refapp#88]
source https://docs.google.com/document/d/1ueWUTrKcFNKpOSFyQ4Vpcv7TAC6GbmamGQnj-J9pefI/edit

Currently, blurbs are actually too long. 

New one
![Screenshot 2022-04-17 at 4 44 24 PM](https://user-images.githubusercontent.com/46257909/163736543-8b0027c5-017a-4930-b79d-cb04e2bbfdf2.png)

Before: 
![Screenshot 2022-04-17 at 4 45 17 PM](https://user-images.githubusercontent.com/46257909/163736532-bbbb7f3a-f21e-47f5-a226-d9667241f464.png)

I will put the full blurb into the readme.md page as a quick solution.

**Comment by maxhsu-da** [comment]
Addressed
